<script src="{{ asset('assets/js/core/app.js') }}"></script> {{-- BS Jquery --}}
<script src="{{ asset('assets/js/utils/js.cookie.js') }}"></script> {{-- Cookie --}}
<script src="{{ asset('assets/js/core/argon.js') }}?v=1.2.0"></script> {{-- Argon --}}
<script src="{{ asset('assets/js/utils/datatables.min.js') }}"></script> {{-- DT --}}
<script src="{{ asset('assets/js/utils/datatables.rowReorder.min.js') }}"></script>
<script src="{{ asset('assets/js/utils/datatables.responsive.min.js') }}"></script>
<script src="{{ asset('assets/js/utils/datatables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/utils/datatables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/js/utils/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/utils/jszip.min.js') }}"></script>
<script src="{{ asset('assets/js/utils/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/js/utils/vfs_fonts.min.js') }}"></script>
<script src="{{ asset('assets/js/utils/html5.min.js') }}"></script>
<script src="{{ asset('assets/js/utils/print.js') }}"></script>
<script src="{{ asset('assets/js/utils/sweetalert.min.js') }}"></script> {{-- SA --}}
<script src="{{ asset('assets/js/utils/select2.min.js') }}"></script> {{-- Select --}}
<script src="{{ asset('assets/js/utils/filepond.js') }}"></script> {{-- FP --}}
<script src="{{ asset('assets/js/utils/filepond-plugin-file-validate-size.js') }}"></script>
<script src="{{ asset('assets/js/utils/filepond-plugin-file-validate-type.js') }}"></script>
<script src="{{ asset('assets/js/utils/toastr.min.js') }}"></script> {{-- Notif --}}
<script src="{{ asset('assets/js/shared/utils.js') }}"></script> {{-- Utils --}}
<script src="{{ asset('assets/js/shared/crud.js') }}"></script>
