{{-- blade-formatter-disable --}}
@component('mail::message')
Dear <strong> {{ $user->resident->full_name }}</strong>, <br> <br>
Your account is now activated. You can now use your E-Barangay System account to access our platform.
@component('mail::panel')
Account Credential <br>
Email: {{ $user->email }} <br>
Password: {{ $password }} <br>
@endcomponent
<small>Note - This is a system autogenerated password. For security purposes please update your password as soon as you login
to the system.</small>
<br><br>
Thanks,<br>
{{ config('app.name') }}
@endcomponent
